%grupo_cristalino.
grupo_cristalino('afganita','cubo').
grupo_cristalino('almandina','cubo').
grupo_cristalino('analcima','cubo').
grupo_cristalino('bismuto','cubo').
grupo_cristalino('bixbita','cubo').
grupo_cristalino('bornita','cubo').
grupo_cristalino('calomel','cubo').
grupo_cristalino('calcopirita','cubo').
grupo_cristalino('cobre','cubo').
grupo_cristalino('criolita','cubo').
grupo_cristalino('cuprita','cubo').
grupo_cristalino('diamante','cubo').
grupo_cristalino('fluorita','cubo').
grupo_cristalino('galena','cubo').
grupo_cristalino('oro','cubo').
grupo_cristalino('halit','cubo').
grupo_cristalino('hierro-niquel','cubo').
grupo_cristalino('plomo','cubo').
grupo_cristalino('leucita','cubo').
grupo_cristalino('magnetita','cubo').
grupo_cristalino('melanoflogita','cubo').
grupo_cristalino('mercurio','cubo').
grupo_cristalino('nitratina','cubo').
grupo_cristalino('platino','cubo').
grupo_cristalino('pirita','cubo').
grupo_cristalino('plata','cubo').
grupo_cristalino('sodalita','cubo').
grupo_cristalino('esfalerita','cubo').
grupo_cristalino('espinela','cubo').
grupo_cristalino('silvita','cubo').
grupo_cristalino('tennantita','cubo').
grupo_cristalino('uraninita','cubo').
grupo_cristalino('berilo','hexagonal').
grupo_cristalino('citrina','hexagonal').
grupo_cristalino('esmeralda','hexagonal').
grupo_cristalino('grafito','hexagonal').
grupo_cristalino('hielo','hexagonal').
grupo_cristalino('pirrotita','hexagonal').
grupo_cristalino('cuarzo','hexagonal').
grupo_cristalino('rheniita','hexagonal').
grupo_cristalino('safflorita','hexagonal').
grupo_cristalino('wurtzita','hexagonal').
grupo_cristalino('cincita','hexagonal').
grupo_cristalino('actinolita','monoclinico').
grupo_cristalino('aegirina','monoclinico').
grupo_cristalino('arfvedsonita','monoclinico').
grupo_cristalino('augita','monoclinico').
grupo_cristalino('babingtonita','monoclinico').
grupo_cristalino('bauxita','monoclinico').
grupo_cristalino('biotita','monoclinico').
grupo_cristalino('brucita','monoclinico').
grupo_cristalino('calcocita','monoclinico').
grupo_cristalino('chamosita','monoclinico').
grupo_cristalino('clorita','monoclinico').
grupo_cristalino('crisocola','monoclinico').
grupo_cristalino('clinochlora','monoclinico').
grupo_cristalino('colemanita','monoclinico').
grupo_cristalino('cookeita','monoclinico').
grupo_cristalino('covelita','monoclinico').
grupo_cristalino('crocoita','monoclinico').
grupo_cristalino('diopsida','monoclinico').
grupo_cristalino('dioptasia','monoclinico').
grupo_cristalino('enargita','monoclinico').
grupo_cristalino('epsomita','monoclinico').
grupo_cristalino('eritrita','monoclinico').
grupo_cristalino('glaucofano','monoclinico').
grupo_cristalino('yeso','monoclinico').
grupo_cristalino('hedenbergita','monoclinico').
grupo_cristalino('hemimorfita','monoclinico').
grupo_cristalino('hornblenda','monoclinico').
grupo_cristalino('hidro-zincita','monoclinico').
grupo_cristalino('lawsonita','monoclinico').
grupo_cristalino('lepidolita','monoclinico').
grupo_cristalino('malachita','monoclinico').
grupo_cristalino('metastibnita','monoclinico').
grupo_cristalino('microclina','monoclinico').
grupo_cristalino('millerita','monoclinico').
grupo_cristalino('molibdenita','monoclinico').
grupo_cristalino('moscovita','monoclinico').
grupo_cristalino('omfacita','monoclinico').
grupo_cristalino('orpimenta','monoclinico').
grupo_cristalino('ortoclasa','monoclinico').
grupo_cristalino('pargasita','monoclinico').
grupo_cristalino('pearceita','monoclinico').
grupo_cristalino('pectolita','monoclinico').
grupo_cristalino('flogopita','monoclinico').
grupo_cristalino('proustita','monoclinico').
grupo_cristalino('pirolusita','monoclinico').
grupo_cristalino('pirofilo','monoclinico').
grupo_cristalino('riebeckita','monoclinico').
grupo_cristalino('sanidina','monoclinico').
grupo_cristalino('espodumeno','monoclinico').
grupo_cristalino('estilbita','monoclinico').
grupo_cristalino('azufre','monoclinico').
grupo_cristalino('talco','monoclinico').
grupo_cristalino('tomsonita','monoclinico').
grupo_cristalino('tincalconita','monoclinico').
grupo_cristalino('tremolita','monoclinico').
grupo_cristalino('trifilita','monoclinico').
grupo_cristalino('ulexita','monoclinico').
grupo_cristalino('xantoconita','monoclinico').
grupo_cristalino('adamita','ortorrombico').
grupo_cristalino('alabandita','ortorrombico').
grupo_cristalino('amatista','ortorrombico').
grupo_cristalino('andalusita','ortorrombico').
grupo_cristalino('andradita','ortorrombico').
grupo_cristalino('anglesita','ortorrombico').
grupo_cristalino('anhidrita','ortorrombico').
grupo_cristalino('anabergita','ortorrombico').
grupo_cristalino('anortita','ortorrombico').
grupo_cristalino('antimonio','ortorrombico').
grupo_cristalino('apatita','ortorrombico').
grupo_cristalino('aragonita','ortorrombico').
grupo_cristalino('aurichalcita','ortorrombico').
grupo_cristalino('azurita','ortorrombico').
grupo_cristalino('barita','ortorrombico').
grupo_cristalino('bismutinita','ortorrombico').
grupo_cristalino('boehmita','ortorrombico').
grupo_cristalino('boleita','ortorrombico').
grupo_cristalino('boracita','ortorrombico').
grupo_cristalino('boulangerita','ortorrombico').
grupo_cristalino('bournonita','ortorrombico').
grupo_cristalino('brochantita','ortorrombico').
grupo_cristalino('bromargyrita','ortorrombico').
grupo_cristalino('brookita','ortorrombico').
grupo_cristalino('burgerita','ortorrombico').
grupo_cristalino('bustamita','ortorrombico').
grupo_cristalino('calaverita','ortorrombico').
grupo_cristalino('carletonita','ortorrombico').
grupo_cristalino('cassiterita','ortorrombico').
grupo_cristalino('celestina','ortorrombico').
grupo_cristalino('celsiana','ortorrombico').
grupo_cristalino('cerusita','ortorrombico').
grupo_cristalino('cervantita','ortorrombico').
grupo_cristalino('chabazita','ortorrombico').
grupo_cristalino('chambersita','ortorrombico').
grupo_cristalino('clorargirita','ortorrombico').
grupo_cristalino('condrodita','ortorrombico').
grupo_cristalino('cromita','ortorrombico').
grupo_cristalino('cristalino_de_crisoberyl','ortorrombico').
grupo_cristalino('clinohumita','ortorrombico').
grupo_cristalino('clinozoisita','ortorrombico').
grupo_cristalino('coesite','ortorrombico').
grupo_cristalino('columbita','ortorrombico').
grupo_cristalino('cordierita','ortorrombico').
grupo_cristalino('cristobalita','ortorrombico').
grupo_cristalino('cumengita','ortorrombico').
grupo_cristalino('danburita','ortorrombico').
grupo_cristalino('datolita','ortorrombico').
grupo_cristalino('diaspora','ortorrombico').
grupo_cristalino('dravita','ortorrombico').
grupo_cristalino('dumortierita','ortorrombico').
grupo_cristalino('edenita','ortorrombico').
grupo_cristalino('elbaita','ortorrombico').
grupo_cristalino('enstatita','ortorrombico').
grupo_cristalino('epidota','ortorrombico').
grupo_cristalino('euclasa','ortorrombico').
grupo_cristalino('ferberita','ortorrombico').
grupo_cristalino('franklinita','ortorrombico').
grupo_cristalino('granate','ortorrombico').
grupo_cristalino('gaspeita','ortorrombico').
grupo_cristalino('glauberita','ortorrombico').
grupo_cristalino('gmelinita','ortorrombico').
grupo_cristalino('goethita','ortorrombico').
grupo_cristalino('goosecreekita','ortorrombico').
grupo_cristalino('greenockita','ortorrombico').
grupo_cristalino('grossular','ortorrombico').
grupo_cristalino('gummita','ortorrombico').
grupo_cristalino('hafnon','ortorrombico').
grupo_cristalino('hastingsita','ortorrombico').
grupo_cristalino('hayuena','ortorrombico').
grupo_cristalino('howlite','ortorrombico').
grupo_cristalino('huebnerita','ortorrombico').
grupo_cristalino('humita','ortorrombico').
grupo_cristalino('ilmenita','ortorrombico').
grupo_cristalino('inesite','ortorrombico').
grupo_cristalino('iodargirita','ortorrombico').
grupo_cristalino('jamesonita','ortorrombico').
grupo_cristalino('jarosita','ortorrombico').
grupo_cristalino('jeremejevita','ortorrombico').
grupo_cristalino('johannsenita','ortorrombico').
grupo_cristalino('kernita','ortorrombico').
grupo_cristalino('krennerita','ortorrombico').
grupo_cristalino('lazulita','ortorrombico').
grupo_cristalino('liddicoatita','ortorrombico').
grupo_cristalino('linarita','ortorrombico').
grupo_cristalino('loellingita','ortorrombico').
grupo_cristalino('magnesiochromita','ortorrombico').
grupo_cristalino('magnesita','ortorrombico').
grupo_cristalino('manganita','ortorrombico').
grupo_cristalino('manganoneptunita','ortorrombico').
grupo_cristalino('marcasita','ortorrombico').
grupo_cristalino('marialita','ortorrombico').
grupo_cristalino('meionita','ortorrombico').
grupo_cristalino('mesolita','ortorrombico').
grupo_cristalino('miargirita','ortorrombico').
grupo_cristalino('mimetita','ortorrombico').
grupo_cristalino('monazita','ortorrombico').
grupo_cristalino('natroclita','ortorrombico').
grupo_cristalino('nepheline','ortorrombico').
grupo_cristalino('neptunita','ortorrombico').
grupo_cristalino('nickelina','ortorrombico').
grupo_cristalino('nitrato','ortorrombico').
grupo_cristalino('norbergita','ortorrombico').
grupo_cristalino('noseana','ortorrombico').
grupo_cristalino('olivina','ortorrombico').
grupo_cristalino('olmiita','ortorrombico').
grupo_cristalino('otavita','ortorrombico').
grupo_cristalino('paradamita','ortorrombico').
grupo_cristalino('pentlandita','ortorrombico').
grupo_cristalino('fosgenita','ortorrombico').
grupo_cristalino('polibasita','ortorrombico').
grupo_cristalino('powellite','ortorrombico').
grupo_cristalino('prehnita','ortorrombico').
grupo_cristalino('psilomelana','ortorrombico').
grupo_cristalino('pumpellyita','ortorrombico').
grupo_cristalino('piromorfita','ortorrombico').
grupo_cristalino('pirita-piropo','ortorrombico').
grupo_cristalino('raspita','ortorrombico').
grupo_cristalino('romanecita','ortorrombico').
grupo_cristalino('sal_amoniaco','ortorrombico').
grupo_cristalino('esqueleto','ortorrombico').
grupo_cristalino('schorlomita','ortorrombico').
grupo_cristalino('scolecita','ortorrombico').
grupo_cristalino('escorzalita','ortorrombico').
grupo_cristalino('serandita','ortorrombico').
grupo_cristalino('shattuckita','ortorrombico').
grupo_cristalino('silimanita','ortorrombico').
grupo_cristalino('kuterido','ortorrombico').
grupo_cristalino('smithsonita','ortorrombico').
grupo_cristalino('espersaritina','ortorrombico').
grupo_cristalino('espessartina','ortorrombico').
grupo_cristalino('estaurolita','ortorrombico').
grupo_cristalino('estellerita','ortorrombico').
grupo_cristalino('estefanita','ortorrombico').
grupo_cristalino('estibarsen','ortorrombico').
grupo_cristalino('estibiconita','ortorrombico').
grupo_cristalino('estibnita','ortorrombico').
grupo_cristalino('estishovita','ortorrombico').
grupo_cristalino('estolzita','ortorrombico').
grupo_cristalino('estrengita','ortorrombico').
grupo_cristalino('estroncinita','ortorrombico').
grupo_cristalino('silvanita','ortorrombico').
grupo_cristalino('tantalita','ortorrombico').
grupo_cristalino('telurio','ortorrombico').
grupo_cristalino('tephroita','ortorrombico').
grupo_cristalino('tetrahedrita','ortorrombico').
grupo_cristalino('tenardita','ortorrombico').
grupo_cristalino('torita','ortorrombico').
grupo_cristalino('torogummita','ortorrombico').
grupo_cristalino('titanita','ortorrombico').
grupo_cristalino('topacio','ortorrombico').
grupo_cristalino('turmalina','ortorrombico').
grupo_cristalino('uvarovita','ortorrombico').
grupo_cristalino('uvita','ortorrombico').
grupo_cristalino('vanadinit','ortorrombico').
grupo_cristalino('variscita','ortorrombico').
grupo_cristalino('vesuvianita','ortorrombico').
grupo_cristalino('vivianita','ortorrombico').
grupo_cristalino('wavellite','ortorrombico').
grupo_cristalino('willemita','ortorrombico').
grupo_cristalino('witherita','ortorrombico').
grupo_cristalino('wolframita','ortorrombico').
grupo_cristalino('wollastonita','ortorrombico').
grupo_cristalino('wulfenita','ortorrombico').
grupo_cristalino('xenotima','ortorrombico').
grupo_cristalino('circon','ortorrombico').
grupo_cristalino('zoisita','ortorrombico').
grupo_cristalino('anatasa','tetragonal').
grupo_cristalino('agata','triclinico').
grupo_cristalino('albite','triclinico').
grupo_cristalino('andesina','triclinico').
grupo_cristalino('anortoclasa','triclinico').
grupo_cristalino('arsenopirita','triclinico').
grupo_cristalino('axinita','triclinico').
grupo_cristalino('benitoita','triclinico').
grupo_cristalino('borax','triclinico').
grupo_cristalino('bytownita','triclinico').
grupo_cristalino('chalcanthita','triclinico').
grupo_cristalino('calcedonia','triclinico').
grupo_cristalino('cobalto','triclinico').
grupo_cristalino('cyanotrichita','triclinico').
grupo_cristalino('epistilbita','triclinico').
grupo_cristalino('heulandita','triclinico').
grupo_cristalino('caolinita','triclinico').
grupo_cristalino('cianita','triclinico').
grupo_cristalino('labradorita','triclinico').
grupo_cristalino('laumontita','triclinico').
grupo_cristalino('lazurita','triclinico').
grupo_cristalino('litiophilita','triclinico').
grupo_cristalino('luzonita','triclinico').
grupo_cristalino('metavariscita','triclinico').
grupo_cristalino('natrojarosita','triclinico').
grupo_cristalino('oligoclasa','triclinico').
grupo_cristalino('pararealgar','triclinico').
grupo_cristalino('plagioclasa','triclinico').
grupo_cristalino('pirargirita','triclinico').
grupo_cristalino('realgar','triclinico').
grupo_cristalino('rodonita','triclinico').
grupo_cristalino('escapolita','triclinico').
grupo_cristalino('serpentina','triclinico').
grupo_cristalino('siderita','triclinico').
grupo_cristalino('acanthita','triclinico').
grupo_cristalino('apofilita','triclinico').
grupo_cristalino('tridimita','triclinico').
grupo_cristalino('turquesa','triclinico').
grupo_cristalino('aguamarina','trigonal').
grupo_cristalino('arsenico','trigonal').
grupo_cristalino('caliza','trigonal').
grupo_cristalino('cinabrio','trigonal').
grupo_cristalino('corindon','trigonal').
grupo_cristalino('dolomita','trigonal').
grupo_cristalino('gibbsita','trigonal').
grupo_cristalino('hematita','trigonal').
grupo_cristalino('jadeita','trigonal').
grupo_cristalino('jaspe','trigonal').
grupo_cristalino('limonita','trigonal').
grupo_cristalino('metacinnabar','trigonal').
grupo_cristalino('opala','trigonal').
grupo_cristalino('pezzottaita','trigonal').
grupo_cristalino('fenacita','trigonal').
grupo_cristalino('pyroxmangita','trigonal').
grupo_cristalino('rammelsbergita','trigonal').
grupo_cristalino('rodocrosita','trigonal').
grupo_cristalino('rutilo','trigonal').
grupo_cristalino('trekita','trigonal').
grupo_cristalino('esferocobaltita','trigonal').

%color
color('afganita','azul').
color('almandina','rojo_oscuro').
color('analcima','incoloro').
color('bismuto','gris').
color('bixbita','negro').
color('bornita','multicolor').
color('calomel','amarillo_claro').
color('calcopirita','dorado').
color('cobre','rojo').
color('criolita','incoloro').
color('cuprita','rojo').
color('diamante','incoloro').
color('fluorita','violeta').
color('galena','gris_oscuro').
color('oro','dorado').
color('halit','blanco').
color('hierro-niquel','gris').
color('plomo','gris').
color('leucita','incoloro').
color('magnetita','negro').
color('melanoflogita','gris_oscuro').
color('mercurio','gris').
color('nitratina','incoloro').
color('platino','gris').
color('pirita','amarillo').
color('plata','gris').
color('sodalita','azul').
color('esfalerita','amarillo').
color('espinela','rojo').
color('silvita','blanco').
color('tennantita','gris').
color('uraninita','gris').
color('berilo','varios_colores').
color('citrina','amarillo_dorado').
color('esmeralda','verde_intenso').
color('grafito','gris_oscuro').
color('hielo','blanco').
color('pirrotita','gris').
color('cuarzo','incoloro').
color('rheniita','gris').
color('safflorita','gris').
color('wurtzita','amarillo').
color('cincita','rojo').
color('actinolita','verde_claro').
color('aegirina','verde_oscuro').
color('arfvedsonita','negro').
color('augita','verde_oscuro').
color('babingtonita','blanco').
color('bauxita','gris_claro').
color('biotita','negro').
color('brucita','blanco').
color('calcocita','gris_oscuro').
color('chamosita','verde_claro').
color('clorita','verde').
color('crisocola','azul').
color('clinochlora','verde').
color('colemanita','blanco').
color('cookeita','verde_claro').
color('covelita','azul_claro').
color('crocoita','naranja').
color('diopsida','verde').
color('dioptasia','verde_intenso').
color('enargita','marron').
color('epsomita','blanco').
color('eritrita','rosa_claro').
color('glaucofano','azul').
color('yeso','incoloro').
color('hedenbergita','negro').
color('hemimorfita','azul').
color('hornblenda','gris').
color('hidro-zincita','blanco').
color('lawsonita','azul').
color('lepidolita','rosa').
color('malachita','verde').
color('metastibnita','gris').
color('microclina','blanco').
color('millerita','gris').
color('molibdenita','gris').
color('moscovita','incoloro').
color('omfacita','verde').
color('orpimenta','amarillo').
color('ortoclasa','blanco').
color('pargasita','verde').
color('pearceita','gris').
color('pectolita','blanco').
color('flogopita','amarillo').
color('proustita','rojo').
color('pirolusita','gris').
color('pirofilo','blanco').
color('riebeckita','azul').
color('sanidina','incoloro').
color('espodumeno','incoloro').
color('estilbita','blanco').
color('azufre','amarillo').
color('talco','blanco').
color('tomsonita','blanco').
color('tincalconita','azul').
color('tremolita','verde').
color('trifilita','gris').
color('ulexita','blanco').
color('xantoconita','gris').
color('adamita','verde_claro').
color('alabandita','gris_oscuro').
color('amatista','violeta').
color('andalusita','gris_claro').
color('andradita','verde').
color('anglesita','blanco').
color('anhidrita','blanco').
color('anabergita','verde_oscuro').
color('anortita','blanco').
color('antimonio','gris').
color('apatita','verde').
color('aragonita','blanco').
color('aurichalcita','verde_azulado').
color('azurita','azul_intenso').
color('barita','blanco').
color('bismutinita','gris_oscuro').
color('boehmita','gris_claro').
color('boleita','azul').
color('boracita','blanco').
color('boulangerita','gris_claro').
color('bournonita','gris_oscuro').
color('brochantita','verde_claro').
color('bromargyrita','gris_oscuro').
color('brookita','marron').
color('burgerita','amarillo').
color('bustamita','rosa').
color('calaverita','amarillo').
color('carletonita','gris_claro').
color('cassiterita','gris').
color('celestina','azul').
color('celsiana','amarillo').
color('cerusita','blanco').
color('cervantita','verde_claro').
color('chabazita','blanco').
color('chambersita','azul').
color('clorargirita','gris_oscuro').
color('condrodita','verde_claro').
color('cromita','gris_oscuro').
color('cristalino_de_crisoberyl','amarillo').
color('clinohumita','amarillo').
color('clinozoisita','verde_claro').
color('coesite','incoloro').
color('columbita','gris_oscuro').
color('cordierita','gris').
color('cristobalita','incoloro').
color('cumengita','blanco').
color('danburita','blanco').
color('datolita','blanco').
color('diaspora','amarillo').
color('dravita','marron').
color('dumortierita','azul').
color('edenita','verde_claro').
color('elbaita','rosa').
color('enstatita','gris').
color('epidota','verde_claro').
color('euclasa','azul_claro').
color('ferberita','negro').
color('franklinita','gris_oscuro').
color('granate','rojo').
color('gaspeita','verde_claro').
color('glauberita','blanco').
color('gmelinita','blanco').
color('goethita','marron').
color('goosecreekita','gris_claro').
color('greenockita','amarillo').
color('grossular','verde').
color('gummita','amarillo').
color('hafnon','gris_oscuro').
color('hastingsita','verde_oscuro').
color('hayuena','azul').
color('howlite','blanco').
color('huebnerita','gris_oscuro').
color('humita','amarillo').
color('ilmenita','gris').
color('inesite','blanco').
color('iodargirita','blanco').
color('jamesonita','gris_oscuro').
color('jarosita','amarillo').
color('jeremejevita','incoloro').
color('johannsenita','gris').
color('kernita','blanco').
color('krennerita','gris').
color('lazulita','azul').
color('liddicoatita','rosa').
color('linarita','azul').
color('loellingita','gris_oscuro').
color('magnesiochromita','gris').
color('magnesita','blanco').
color('manganita','marron').
color('manganoneptunita','azul').
color('marcasita','gris').
color('marialita','blanco').
color('meionita','incoloro').
color('mesolita','blanco').
color('miargirita','negro').
color('mimetita','amarillo').
color('monazita','amarillo').
color('natroclita','blanco').
color('nepheline','incoloro').
color('neptunita','azul').
color('nickelina','amarillo').
color('nitrato','blanco').
color('norbergita','gris').
color('noseana','azul').
color('olivina','verde').
color('olmiita','gris').
color('otavita','verde').
color('paradamita','verde').
color('pentlandita','gris').
color('fosgenita','blanco').
color('polibasita','gris').
color('powellite','amarillo').
color('prehnita','verde').
color('psilomelana','negro').
color('pumpellyita','verde').
color('piromorfita','verde').
color('pirita-piropo','rojo').
color('raspita','gris').
color('romanecita','gris').
color('sal_amoniaco','blanco').
color('esqueleto','blanco').
color('schorlomita','gris').
color('scolecita','blanco').
color('escorzalita','gris').
color('serandita','rosa').
color('shattuckita','azul').
color('silimanita','gris').
color('kuterido','gris').
color('smithsonita','amarillo').
color('espersaritina','gris').
color('espessartina','rojo').
color('estaurolita','marron').
color('estellerita','blanco').
color('estefanita','gris').
color('estibarsen','gris').
color('estibiconita','gris').
color('estibnita','gris').
color('estishovita','gris').
color('estolzita','gris').
color('estrengita','morado').
color('estroncinita','blanco').
color('silvanita','gris').
color('tantalita','gris').
color('telurio','gris').
color('tephroita','gris').
color('tetrahedrita','gris').
color('tenardita','blanco').
color('torita','gris').
color('torogummita','gris').
color('titanita','marron').
color('topacio','amarillo').
color('turmalina','varios_colores').
color('uvarovita','verde').
color('uvita','verde').
color('vanadinit','naranja').
color('variscita','verde').
color('vesuvianita','verde').
color('vivianita','azul').
color('wavellite','verde').
color('willemita','verde').
color('witherita','blanco').
color('wolframita','gris').
color('wollastonita','blanco').
color('wulfenita','naranja').
color('xenotima','amarillo').
color('circon','marron').
color('zoisita','verde').
color('anatasa','incoloro').
color('agata','varios_colores').
color('albite','blanco').
color('andesina','rojo').
color('anortoclasa','incoloro').
color('arsenopirita','gris').
color('axinita','marron').
color('benitoita','azul_intenso').
color('borax','blanco').
color('bytownita','blanco').
color('chalcanthita','azul_claro').
color('calcedonia','blanco').
color('cobalto','gris').
color('cyanotrichita','azul').
color('epistilbita','blanco').
color('heulandita','blanco').
color('caolinita','blanco').
color('cianita','azul').
color('labradorita','gris').
color('laumontita','blanco').
color('lazurita','azul_intenso').
color('litiophilita','amarillo').
color('luzonita','blanco').
color('metavariscita','verde').
color('natrojarosita','amarillo').
color('oligoclasa','blanco').
color('pararealgar','anaranjado').
color('plagioclasa','blanco').
color('pirargirita','rojo').
color('realgar','naranja').
color('rodonita','rosa').
color('escapolita','incoloro').
color('serpentina','verde').
color('siderita','gris').
color('acanthita','gris_oscuro').
color('apofilita','blanco').
color('tridimita','blanco').
color('turquesa','azul').
color('aguamarina','azul_claro').
color('arsenico','gris').
color('caliza','blanco').
color('cinabrio','rojo_intenso').
color('corindon','gris').
color('dolomita','gris').
color('gibbsita','blanco').
color('hematita','rojo').
color('jadeita','verde').
color('jaspe','rojo').
color('limonita','amarillo').
color('metacinnabar','rojo').
color('opala','blanco').
color('pezzottaita','rosa').
color('fenacita','incoloro').
color('pyroxmangita','rosa').
color('rammelsbergita','gris').
color('rodocrosita','rosa').
color('rutilo','incoloro').
color('trekita','negro').
color('esferocobaltita','azul').

%raya.
raya('afganita','azul').
raya('almandina','rojo').
raya('analcima','blanco').
raya('bismuto','gris_oscuro').
raya('bixbita','negro').
raya('bornita','gris').
raya('calomel','amarillo').
raya('calcopirita','gris').
raya('cobre','rojo').
raya('criolita','incoloro').
raya('cuprita','rojo').
raya('diamante','incoloro').
raya('fluorita','verde').
raya('galena','gris').
raya('oro','dorado').
raya('halit','blanco').
raya('hierro-niquel','gris').
raya('plomo','gris').
raya('leucita','blanco').
raya('magnetita','negro').
raya('melanoflogita','gris').
raya('mercurio','gris').
raya('nitratina','incoloro').
raya('platino','gris').
raya('pirita','amarillo').
raya('plata','gris').
raya('sodalita','azul').
raya('esfalerita','amarillo').
raya('espinela','rojo').
raya('silvita','blanco').
raya('tennantita','gris').
raya('uraninita','gris').
raya('berilo','blanco').
raya('citrina','amarillo').
raya('esmeralda','verde').
raya('grafito','gris_oscuro').
raya('hielo','incoloro').
raya('pirrotita','gris').
raya('cuarzo','incoloro').
raya('rheniita','gris').
raya('safflorita','gris').
raya('wurtzita','amarillo').
raya('cincita','rojo').
raya('actinolita','blanco').
raya('aegirina','verde').
raya('arfvedsonita','gris_oscuro').
raya('augita','gris').
raya('babingtonita','gris').
raya('bauxita','gris').
raya('biotita','gris').
raya('brucita','blanco').
raya('calcocita','gris').
raya('chamosita','verde').
raya('clorita','verde').
raya('crisocola','azul_claro').
raya('clinochlora','verde').
raya('colemanita','blanco').
raya('cookeita','gris').
raya('covelita','azul').
raya('crocoita','rojo').
raya('diopsida','verde').
raya('dioptasia','verde').
raya('enargita','gris').
raya('epsomita','blanco').
raya('eritrita','rosa_claro').
raya('glaucofano','azul').
raya('yeso','blanco').
raya('hedenbergita','negro').
raya('hemimorfita','blanco').
raya('hornblenda','gris').
raya('hidro-zincita','blanco').
raya('lawsonita','blanco').
raya('lepidolita','rosa').
raya('malachita','verde').
raya('metastibnita','gris').
raya('microclina','blanco').
raya('millerita','gris').
raya('molibdenita','gris').
raya('moscovita','blanco').
raya('omfacita','verde').
raya('orpimenta','amarillo').
raya('ortoclasa','blanco').
raya('pargasita','verde').
raya('pearceita','gris').
raya('pectolita','blanco').
raya('flogopita','amarillo').
raya('proustita','rojo').
raya('pirolusita','gris').
raya('pirofilo','blanco').
raya('riebeckita','azul').
raya('sanidina','incoloro').
raya('espodumeno','incoloro').
raya('estilbita','blanco').
raya('azufre','amarillo').
raya('talco','blanco').
raya('tomsonita','blanco').
raya('tincalconita','azul').
raya('tremolita','verde').
raya('trifilita','gris').
raya('ulexita','blanco').
raya('xantoconita','gris').
raya('adamita','blanco').
raya('alabandita','gris').
raya('amatista','blanco').
raya('andalusita','blanco').
raya('andradita','blanco').
raya('anglesita','blanco').
raya('anhidrita','blanco').
raya('anabergita','verde').
raya('anortita','blanco').
raya('antimonio','gris').
raya('apatita','verde').
raya('aragonita','blanco').
raya('aurichalcita','gris').
raya('azurita','azul').
raya('barita','blanco').
raya('bismutinita','gris').
raya('boehmita','gris').
raya('boleita','gris').
raya('boracita','blanco').
raya('boulangerita','gris').
raya('bournonita','gris').
raya('brochantita','verde').
raya('bromargyrita','gris_oscuro').
raya('brookita','marron').
raya('burgerita','gris').
raya('bustamita','gris').
raya('calaverita','gris').
raya('carletonita','gris').
raya('cassiterita','gris').
raya('celestina','azul').
raya('celsiana','blanco').
raya('cerusita','blanco').
raya('cervantita','gris').
raya('chabazita','blanco').
raya('chambersita','azul').
raya('clorargirita','gris').
raya('condrodita','verde').
raya('cromita','gris').
raya('cristalino_de_crisoberyl','blanco').
raya('clinohumita','amarillo').
raya('clinozoisita','verde').
raya('coesite','incoloro').
raya('columbita','gris').
raya('cordierita','gris').
raya('cristobalita','incoloro').
raya('cumengita','gris').
raya('danburita','blanco').
raya('datolita','blanco').
raya('diaspora','blanco').
raya('dravita','marron').
raya('dumortierita','gris_oscuro').
raya('edenita','gris_claro').
raya('elbaita','rosa').
raya('enstatita','gris').
raya('epidota','verde').
raya('euclasa','azul_claro').
raya('ferberita','gris_oscuro').
raya('franklinita','gris').
raya('granate','gris').
raya('gaspeita','verde_claro').
raya('glauberita','gris_claro').
raya('gmelinita','blanco').
raya('goethita','gris').
raya('goosecreekita','gris_claro').
raya('greenockita','gris_claro').
raya('grossular','verde').
raya('gummita','amarillo').
raya('hafnon','gris').
raya('hastingsita','verde_oscuro').
raya('hayuena','azul').
raya('howlite','gris_claro').
raya('huebnerita','gris').
raya('humita','amarillo').
raya('ilmenita','gris').
raya('inesite','blanco').
raya('iodargirita','blanco').
raya('jamesonita','gris_oscuro').
raya('jarosita','amarillo').
raya('jeremejevita','incoloro').
raya('johannsenita','gris_oscuro').
raya('kernita','blanco').
raya('krennerita','gris').
raya('lazulita','azul').
raya('liddicoatita','rosa').
raya('linarita','azul').
raya('loellingita','gris').
raya('magnesiochromita','gris_oscuro').
raya('magnesita','blanco').
raya('manganita','marron').
raya('manganoneptunita','azul').
raya('marcasita','gris').
raya('marialita','blanco').
raya('meionita','incoloro').
raya('mesolita','blanco').
raya('miargirita','gris_oscuro').
raya('mimetita','amarillo').
raya('monazita','amarillo').
raya('natroclita','blanco').
raya('nepheline','incoloro').
raya('neptunita','azul').
raya('nickelina','amarillo').
raya('nitrato','blanco').
raya('norbergita','gris').
raya('noseana','azul').
raya('olivina','verde').
raya('olmiita','gris_oscuro').
raya('otavita','verde').
raya('paradamita','verde').
raya('pentlandita','gris').
raya('fosgenita','blanco').
raya('polibasita','gris').
raya('powellite','amarillo').
raya('prehnita','verde').
raya('psilomelana','gris').
raya('pumpellyita','verde').
raya('piromorfita','verde').
raya('pirita-piropo','rojo').
raya('raspita','gris').
raya('romanecita','gris').
raya('sal_amoniaco','blanco').
raya('esqueleto','blanco').
raya('schorlomita','gris').
raya('scolecita','blanco').
raya('escorzalita','gris').
raya('serandita','rosa').
raya('shattuckita','azul').
raya('silimanita','gris').
raya('kuterido','gris').
raya('smithsonita','amarillo').
raya('espersaritina','gris').
raya('espessartina','rojo').
raya('estaurolita','marron').
raya('estellerita','blanco').
raya('estefanita','gris').
raya('estibarsen','gris').
raya('estibiconita','gris').
raya('estibnita','gris').
raya('estishovita','gris').
raya('estolzita','gris').
raya('estrengita','morado').
raya('estroncinita','blanco').
raya('silvanita','gris').
raya('tantalita','gris').
raya('telurio','gris').
raya('tephroita','gris').
raya('tetrahedrita','gris').
raya('tenardita','blanco').
raya('torita','gris').
raya('torogummita','gris').
raya('titanita','marron').
raya('topacio','amarillo').
raya('turmalina','varioscolores').
raya('uvarovita','verde').
raya('uvita','verde').
raya('vanadinit','naranja').
raya('variscita','verde').
raya('vesuvianita','verde').
raya('vivianita','azul').
raya('wavellite','verde').
raya('willemita','verde').
raya('witherita','blanco').
raya('wolframita','gris').
raya('wollastonita','blanco').
raya('wulfenita','naranja').
raya('xenotima','amarillo').
raya('circon','marron').
raya('zoisita','verde').
raya('anatasa','blanco').
raya('agata','blanco').
raya('albite','blanco').
raya('andesina','blanco').
raya('anortoclasa','blanco').
raya('arsenopirita','gris').
raya('axinita','marron').
raya('benitoita','azul').
raya('borax','blanco').
raya('bytownita','blanco').
raya('chalcanthita','azul').
raya('calcedonia','blanco').
raya('cobalto','gris').
raya('cyanotrichita','azul').
raya('epistilbita','blanco').
raya('heulandita','blanco').
raya('caolinita','blanco').
raya('cianita','azul').
raya('labradorita','gris').
raya('laumontita','blanco').
raya('lazurita','azulintenso').
raya('litiophilita','amarillo').
raya('luzonita','blanco').
raya('metavariscita','verde').
raya('natrojarosita','amarillo').
raya('oligoclasa','blanco').
raya('pararealgar','anaranjado').
raya('plagioclasa','blanco').
raya('pirargirita','rojo').
raya('realgar','naranja').
raya('rodonita','rosa').
raya('escapolita','incoloro').
raya('serpentina','verde').
raya('siderita','gris').
raya('acanthita','gris').
raya('apofilita','blanco').
raya('tridimita','blanco').
raya('turquesa','azul').
raya('aguamarina','blanco').
raya('arsenico','gris').
raya('caliza','blanco').
raya('cinabrio','rojo').
raya('corindon','gris').
raya('dolomita','blanco').
raya('gibbsita','blanco').
raya('hematita','rojo').
raya('jadeita','blanco').
raya('jaspe','rojo').
raya('limonita','amarillo').
raya('metacinnabar','rojo').
raya('opala','blanco').
raya('pezzottaita','rosa').
raya('fenacita','incoloro').
raya('pyroxmangita','rosa').
raya('rammelsbergita','gris').
raya('rodocrosita','rosa').
raya('rutilo','incoloro').
raya('trekita','gris').
raya('esferocobaltita','azul').

%dureza.
dureza('afganita',5,5.5).
dureza('almandina',7.5,8).
dureza('analcima',5,5.5).
dureza('bismuto',2.2,2.4).
dureza('bixbita',5.0,6.0).
dureza('bornita',3.0,4.0).
dureza('calomel',1.5,2).
dureza('calcopirita',3.5,4).
dureza('cobre',2.5,3).
dureza('criolita',2.5,3).
dureza('cuprita',3.5,4).
dureza('diamante',10,10).
dureza('fluorita',4,4).
dureza('galena',2.5,2.5).
dureza('oro',2.5,3).
dureza('halit',2.5,2.5).
dureza('hierro-niquel',6,6.5).
dureza('plomo',2.5,2.5).
dureza('leucita',5.5,5.5).
dureza('magnetita',5.5,6).
dureza('melanoflogita',4,4.5).
dureza('mercurio',2.5,2.5).
dureza('nitratina',5,5.5).
dureza('platino',4,4.5).
dureza('pirita',6,6.5).
dureza('plata',2.5,3).
dureza('sodalita',5.5,6).
dureza('esfalerita',3.5,4).
dureza('espinela',7.5,7.5).
dureza('silvita',2,2.5).
dureza('tennantita',3.5,4).
dureza('uraninita',4.5,5.5).
dureza('berilo',7.5,8).
dureza('citrina',6.5,7).
dureza('esmeralda',7.5,8).
dureza('grafito',1.0,2.0).
dureza('hielo',1,1).
dureza('pirrotita',3.5,4.5).
dureza('cuarzo',7,7).
dureza('rheniita',5,5.5).
dureza('safflorita',5,5.5).
dureza('wurtzita',4.5,5).
dureza('cincita',5.5,5.5).
dureza('actinolita',5.0,6.0).
dureza('aegirina',6.5,7).
dureza('arfvedsonita',5.5,6).
dureza('augita',5.5,6).
dureza('babingtonita',6,6.5).
dureza('bauxita',2.5,3).
dureza('biotita',2.5,3).
dureza('brucita',2.5,2.5).
dureza('calcocita',2,2.5).
dureza('chamosita',2.5,3).
dureza('clorita',2.0,3.0).
dureza('crisocola',2.5,4).
dureza('clinochlora',2.5,4).
dureza('colemanita',3.5,4).
dureza('cookeita',4,4.5).
dureza('covelita',2.5,3).
dureza('crocoita',2.5,3).
dureza('diopsida',5.5,6.5).
dureza('dioptasia',5,5.5).
dureza('enargita',2,2.5).
dureza('epsomita',2,2).
dureza('eritrita',2,2.5).
dureza('glaucofano',5.5,5.5).
dureza('yeso',2,2).
dureza('hedenbergita',6.5,7).
dureza('hemimorfita',4.5,5.5).
dureza('hornblenda',5.0,6.0).
dureza('hidro-zincita',3.5,4).
dureza('lawsonita',4,4.5).
dureza('lepidolita',2.5,3).
dureza('malachita',3.5,4).
dureza('metastibnita',2.5,3).
dureza('microclina',6,6.5).
dureza('millerita',3.0,4.0).
dureza('molibdenita',1.5,2).
dureza('moscovita',2,2.5).
dureza('omfacita',5.5,6).
dureza('orpimenta',1.5,2).
dureza('ortoclasa',6,6.5).
dureza('pargasita',5.0,6.0).
dureza('pearceita',2.5,2.5).
dureza('pectolita',4.5,4.5).
dureza('flogopita',2.0,3.0).
dureza('proustita',3,3.5).
dureza('pirolusita',2,2.5).
dureza('pirofilo',1.0,2.0).
dureza('riebeckita',5.0,6.0).
dureza('sanidina',6.5,7).
dureza('espodumeno',6.5,7.5).
dureza('estilbita',3.5,4).
dureza('azufre',1.5,2).
dureza('talco',1,1).
dureza('tomsonita',5,5.5).
dureza('tincalconita',3,3.5).
dureza('tremolita',5.0,6.0).
dureza('trifilita',5.5,6).
dureza('ulexita',2.5,3).
dureza('xantoconita',3.5,3.5).
dureza('adamita',4.5,5).
dureza('alabandita',3.0,4.0).
dureza('amatista',7,7).
dureza('andalusita',6.5,7).
dureza('andradita',6.5,7).
dureza('anglesita',3.5,4).
dureza('anhidrita',3.5,4).
dureza('anabergita',4,4.5).
dureza('anortita',6,6.5).
dureza('antimonio',2,2.5).
dureza('apatita',5,5).
dureza('aragonita',3.5,4).
dureza('aurichalcita',4.5,5).
dureza('azurita',3.5,4).
dureza('barita',3,3.5).
dureza('bismutinita',2,2.5).
dureza('boehmita',3.5,4).
dureza('boleita',4.5,5).
dureza('boracita',6,6.5).
dureza('boulangerita',2.5,3).
dureza('bournonita',3.5,4).
dureza('brochantita',3.5,4).
dureza('bromargyrita',2,2.5).
dureza('brookita',5.5,6).
dureza('burgerita',6,6.5).
dureza('bustamita',4,4.5).
dureza('calaverita',2,2.5).
dureza('carletonita',2.5,2.5).
dureza('cassiterita',6.5,7).
dureza('celestina',3.5,4).
dureza('celsiana',5.0,6.0).
dureza('cerusita',3.5,4).
dureza('cervantita',3,3.5).
dureza('chabazita',3.5,4).
dureza('chambersita',4,4.5).
dureza('clorargirita',2.5,3).
dureza('condrodita',5,5.5).
dureza('cromita',5.5,6).
dureza('cristalino_de_crisoberyl',8.5,8.5).
dureza('clinohumita',5.5,6).
dureza('clinozoisita',6.5,6.5).
dureza('coesite',7,7.5).
dureza('columbita',5.5,6).
dureza('cordierita',7,7.5).
dureza('cristobalita',7,7.5).
dureza('cumengita',3.0,4.0).
dureza('danburita',7,7.5).
dureza('datolita',5,5.5).
dureza('diaspora',6.5,7).
dureza('dravita',6.0,7.0).
dureza('dumortierita',7.0,8.0).
dureza('edenita',5.5,6).
dureza('elbaita',7,7.5).
dureza('enstatita',5.5,6.5).
dureza('epidota',6.0,7.0).
dureza('euclasa',7.5,7.5).
dureza('ferberita',5,5.5).
dureza('franklinita',5.5,6).
dureza('granate',6.5,7.5).
dureza('gaspeita',2.5,2.5).
dureza('glauberita',3,3.5).
dureza('gmelinita',3.0,4.0).
dureza('goethita',5,5.5).
dureza('goosecreekita',5.5,6).
dureza('greenockita',4,4.5).
dureza('grossular',6.5,7).
dureza('gummita',2,2.5).
dureza('hafnon',6,6.5).
dureza('hastingsita',5.0,6.0).
dureza('hayuena',5.0,6.0).
dureza('howlite',3.5,4).
dureza('huebnerita',5.5,6).
dureza('humita',5.5,6).
dureza('ilmenita',5.0,6.0).
dureza('inesite',5,5.5).
dureza('iodargirita',2.5,2.5).
dureza('jamesonita',2.5,2.5).
dureza('jarosita',3,3.5).
dureza('jeremejevita',6,6.5).
dureza('johannsenita',6.5,7).
dureza('kernita',4.5,5).
dureza('krennerita',5.5,6).
dureza('lazulita',5,5.5).
dureza('liddicoatita',6.5,7).
dureza('linarita',2.5,3).
dureza('loellingita',5,5.5).
dureza('magnesiochromita',5.5,5.5).
dureza('magnesita',3.5,3.5).
dureza('manganita',4,4.5).
dureza('manganoneptunita',5,5.5).
dureza('marcasita',6.5,6.5).
dureza('marialita',6,6.5).
dureza('meionita',5.5,6).
dureza('mesolita',5,5.5).
dureza('miargirita',3,3.5).
dureza('mimetita',3.5,4).
dureza('monazita',4.5,5).
dureza('natroclita',5,5.5).
dureza('nepheline',5.5,6).
dureza('neptunita',5,5.5).
dureza('nickelina',5,5.5).
dureza('nitrato',1.5,1.5).
dureza('norbergita',6,6.5).
dureza('noseana',5,5.5).
dureza('olivina',6.5,7).
dureza('olmiita',5,5.5).
dureza('otavita',4.5,5).
dureza('paradamita',3,3.5).
dureza('pentlandita',3.5,4).
dureza('fosgenita',2.5,3).
dureza('polibasita',2,2.5).
dureza('powellite',4,4.5).
dureza('prehnita',6,6.5).
dureza('psilomelana',2.0,3.0).
dureza('pumpellyita',4.0,5.0).
dureza('piromorfita',3.5,4).
dureza('pirita-piropo',6.5,7).
dureza('raspita',2,2.5).
dureza('romanecita',3,3.5).
dureza('sal_amoniaco',2.5,2.5).
dureza('esqueleto',4.5,5).
dureza('schorlomita',3,3.5).
dureza('scolecita',3.5,4).
dureza('escorzalita',3.5,4).
dureza('serandita',4.5,5).
dureza('shattuckita',5,5).
dureza('silimanita',6.0,7.0).
dureza('kuterido',5,5.5).
dureza('smithsonita',4.5,5).
dureza('espersaritina',6.5,7).
dureza('espessartina',6.5,7).
dureza('estaurolita',7,7.5).
dureza('estellerita',4.0,5.0).
dureza('estefanita',2.0,3.0).
dureza('estibarsen',3.0,4.0).
dureza('estibiconita',2,2.5).
dureza('estibnita',2,2.5).
dureza('estishovita',9,9).
dureza('estolzita',2,2.5).
dureza('estrengita',3.5,4).
dureza('estroncinita',3,3.5).
dureza('silvanita',2,2.5).
dureza('tantalita',6.5,7).
dureza('telurio',2.5,3).
dureza('tephroita',5.5,6.5).
dureza('tetrahedrita',3.5,4).
dureza('tenardita',4.5,4.5).
dureza('torita',4.5,5).
dureza('torogummita',5.0,6.0).
dureza('titanita',5.0,6.0).
dureza('topacio',8,8).
dureza('turmalina',7,7.5).
dureza('uvarovita',6.5,7).
dureza('uvita',6.0,7.0).
dureza('vanadinit',3,3.5).
dureza('variscita',3.5,4).
dureza('vesuvianita',6.5,7).
dureza('vivianita',3.5,4).
dureza('wavellite',3,3.5).
dureza('willemita',5.5,5.5).
dureza('witherita',3,3.5).
dureza('wolframita',4.5,5.5).
dureza('wollastonita',4.0,5.0).
dureza('wulfenita',3.5,4).
dureza('xenotima',4.5,4.5).
dureza('circon',6.0,7.0).
dureza('zoisita',6.0,7.0).
dureza('anatasa',5,5.5).
dureza('agata',6.5,7).
dureza('albite',6,6.5).
dureza('andesina',6.5,7).
dureza('anortoclasa',6,6.5).
dureza('arsenopirita',5.5,6.5).
dureza('axinita',6.5,7).
dureza('benitoita',6.5,7).
dureza('borax',2.5,3).
dureza('bytownita',6,6.5).
dureza('chalcanthita',2.5,3).
dureza('calcedonia',6.5,7).
dureza('cobalto',5.5,6).
dureza('cyanotrichita',3.5,4).
dureza('epistilbita',3.5,3.5).
dureza('heulandita',3.5,4).
dureza('caolinita',2,2.5).
dureza('cianita',4.5,5).
dureza('labradorita',6,6.5).
dureza('laumontita',3.5,4).
dureza('lazurita',5.5,6).
dureza('litiophilita',4.5,4.5).
dureza('luzonita',3.5,3.5).
dureza('metavariscita',3.5,4).
dureza('natrojarosita',3.5,4).
dureza('oligoclasa',6,6.5).
dureza('pararealgar',1.5,2).
dureza('plagioclasa',6,6.5).
dureza('pirargirita',2.0,3.0).
dureza('realgar',1.5,1.5).
dureza('rodonita',5.5,6.5).
dureza('escapolita',5.5,6).
dureza('serpentina',2.5,4).
dureza('siderita',3.5,4).
dureza('acanthita',2,2.5).
dureza('apofilita',4.5,5).
dureza('tridimita',7,7).
dureza('turquesa',5.0,6.0).
dureza('aguamarina',7.5,7.5).
dureza('arsenico',2,2.5).
dureza('caliza',3,3).
dureza('cinabrio',2,2.5).
dureza('corindon',9,9).
dureza('dolomita',3.5,4).
dureza('gibbsita',2.5,3).
dureza('hematita',5.5,6.5).
dureza('jadeita',6.5,7).
dureza('jaspe',6.5,6.5).
dureza('limonita',4.0,5.0).
dureza('metacinnabar',2,2.5).
dureza('opala',5.5,5.5).
dureza('pezzottaita',6.0,7.0).
dureza('fenacita',7.5,8).
dureza('pyroxmangita',6.5,7).
dureza('rammelsbergita',4.5,4.5).
dureza('rodocrosita',3.5,4).
dureza('rutilo',6,6.5).
dureza('trekita',7,7.5).
dureza('esferocobaltita',5,5.5).

%densidad.
densidad('afganita',2.7,3.1).
densidad('almandina',3.9,3.9).
densidad('analcima',2.2,2.4).
densidad('bismuto',9.8,9.8).
densidad('bixbita',5.3,5.3).
densidad('bornita',5,5).
densidad('calomel',5.3,5.3).
densidad('calcopirita',4.2,4.2).
densidad('cobre',8.9,8.9).
densidad('criolita',3,3).
densidad('cuprita',6,6).
densidad('diamante',3.5,3.5).
densidad('fluorita',3.2,3.2).
densidad('galena',7.6,7.6).
densidad('oro',19.3,19.3).
densidad('halit',2.2,2.2).
densidad('hierro-niquel',8.8,8.8).
densidad('plomo',11.3,11.3).
densidad('leucita',2.5,2.5).
densidad('magnetita',5.2,5.2).
densidad('melanoflogita',3.4,3.4).
densidad('mercurio',13.6,13.6).
densidad('nitratina',1.9,1.9).
densidad('platino',21.4,21.4).
densidad('pirita',5,5).
densidad('plata',10.5,10.5).
densidad('sodalita',2.4,2.4).
densidad('esfalerita',3.9,3.9).
densidad('espinela',3.5,3.5).
densidad('silvita',2.1,2.1).
densidad('tennantita',6.1,6.1).
densidad('uraninita',9.2,9.2).
densidad('berilo',2.6,2.9).
densidad('citrina',2.7,2.7).
densidad('esmeralda',2.7,2.7).
densidad('grafito',2.2,2.2).
densidad('hielo',0.9,0.9).
densidad('pirrotita',4.5,4.5).
densidad('cuarzo',2.65,2.65).
densidad('rheniita',10.3,10.3).
densidad('safflorita',7.9,7.9).
densidad('wurtzita',4.1,4.1).
densidad('cincita',5.6,5.6).
densidad('actinolita',2.8,3.3).
densidad('aegirina',3.2,3.4).
densidad('arfvedsonita',3.1,3.3).
densidad('augita',3.1,3.3).
densidad('babingtonita',3.5,3.5).
densidad('bauxita',2.4,2.4).
densidad('biotita',2.8,3.1).
densidad('brucita',2.3,2.3).
densidad('calcocita',5.7,5.7).
densidad('chamosita',3,3).
densidad('clorita',2.6,2.6).
densidad('crisocola',2,2).
densidad('clinochlora',2.6,2.6).
densidad('colemanita',2.8,2.8).
densidad('cookeita',2.6,2.6).
densidad('covelita',5.8,5.8).
densidad('crocoita',6,6).
densidad('diopsida',3.2,3.2).
densidad('dioptasia',3.3,3.3).
densidad('enargita',4.5,4.5).
densidad('epsomita',1.7,1.7).
densidad('eritrita',3.4,3.4).
densidad('glaucofano',3.2,3.2).
densidad('yeso',2.3,2.3).
densidad('hedenbergita',3.3,3.3).
densidad('hemimorfita',4.3,4.3).
densidad('hornblenda',2.9,2.9).
densidad('hidro-zincita',4.3,4.3).
densidad('lawsonita',2.6,2.6).
densidad('lepidolita',2.8,2.8).
densidad('malachita',4,4).
densidad('metastibnita',6.4,6.4).
densidad('microclina',2.6,2.6).
densidad('millerita',5.9,5.9).
densidad('molibdenita',4.6,4.6).
densidad('moscovita',2.8,2.8).
densidad('omfacita',3.1,3.1).
densidad('orpimenta',3.5,3.5).
densidad('ortoclasa',2.6,2.6).
densidad('pargasita',3.3,3.3).
densidad('pearceita',8,8).
densidad('pectolita',2.5,2.5).
densidad('flogopita',2.8,2.8).
densidad('proustita',6.1,6.1).
densidad('pirolusita',4.8,4.8).
densidad('pirofilo',2.8,2.8).
densidad('riebeckita',2.9,2.9).
densidad('sanidina',2.5,2.5).
densidad('espodumeno',3.1,3.1).
densidad('estilbita',2.1,2.1).
densidad('azufre',2,2).
densidad('talco',2.7,2.7).
densidad('tomsonita',2.2,2.2).
densidad('tincalconita',1.9,1.9).
densidad('tremolita',2.9,2.9).
densidad('trifilita',3.2,3.2).
densidad('ulexita',1.9,1.9).
densidad('xantoconita',6,6).
densidad('adamita',4.2,4.2).
densidad('alabandita',7.5,7.5).
densidad('amatista',2.65,2.65).
densidad('andalusita',3.2,3.3).
densidad('andradita',3.8,3.8).
densidad('anglesita',6.2,6.2).
densidad('anhidrita',2.9,2.9).
densidad('anabergita',5.4,5.4).
densidad('anortita',3.3,3.3).
densidad('antimonio',6.7,7.5).
densidad('apatita',3.1,3.3).
densidad('aragonita',2.9,2.9).
densidad('aurichalcita',4.5,4.5).
densidad('azurita',3.8,3.8).
densidad('barita',4.5,4.5).
densidad('bismutinita',7,7).
densidad('boehmita',3.4,3.4).
densidad('boleita',3.8,3.8).
densidad('boracita',3.1,3.1).
densidad('boulangerita',6,6).
densidad('bournonita',6.4,6.4).
densidad('brochantita',4,4).
densidad('bromargyrita',6.5,6.5).
densidad('brookita',4,4).
densidad('burgerita',4.2,4.2).
densidad('bustamita',6,6).
densidad('calaverita',9.2,9.2).
densidad('carletonita',6,6).
densidad('cassiterita',6.7,6.7).
densidad('celestina',3.9,3.9).
densidad('celsiana',2.6,2.6).
densidad('cerusita',6.4,6.4).
densidad('cervantita',3.5,3.5).
densidad('chabazita',2.1,2.1).
densidad('chambersita',3.4,3.4).
densidad('clorargirita',6.4,6.4).
densidad('condrodita',3.3,3.3).
densidad('cromita',4.8,4.8).
densidad('cristalino_de_crisoberyl',3.7,3.7).
densidad('clinohumita',2.8,2.8).
densidad('clinozoisita',3.4,3.4).
densidad('coesite',2.3,2.3).
densidad('columbita',5.2,5.2).
densidad('cordierita',2.6,2.6).
densidad('cristobalita',2.3,2.3).
densidad('cumengita',4.4,4.4).
densidad('danburita',2.9,2.9).
densidad('datolita',3,3).
densidad('diaspora',3.4,3.4).
densidad('dravita',3.1,3.1).
densidad('dumortierita',3.2,3.2).
densidad('edenita',3.2,3.2).
densidad('elbaita',3.1,3.1).
densidad('enstatita',3.2,3.2).
densidad('epidota',3.4,3.4).
densidad('euclasa',3.1,3.1).
densidad('ferberita',7.4,7.4).
densidad('franklinita',5.3,5.3).
densidad('granate',3.6,3.6).
densidad('gaspeita',4.5,4.5).
densidad('glauberita',2.7,2.7).
densidad('gmelinita',2.2,2.2).
densidad('goethita',4.3,4.3).
densidad('goosecreekita',5.5,5.5).
densidad('greenockita',7.4,7.4).
densidad('grossular',3.6,3.6).
densidad('gummita',3.3,3.3).
densidad('hafnon',8.5,8.5).
densidad('hastingsita',3.1,3.1).
densidad('hayuena',2.4,2.4).
densidad('howlite',2.6,2.6).
densidad('huebnerita',7.5,7.5).
densidad('humita',3.2,3.2).
densidad('ilmenita',4.7,4.7).
densidad('inesite',2.8,2.8).
densidad('iodargirita',7.2,7.2).
densidad('jamesonita',6.4,6.4).
densidad('jarosita',3.2,3.2).
densidad('jeremejevita',3.3,3.3).
densidad('johannsenita',3.3,3.3).
densidad('kernita',1.9,1.9).
densidad('krennerita',10.2,10.2).
densidad('lazulita',3.1,3.1).
densidad('liddicoatita',3.2,3.2).
densidad('linarita',5.6,5.6).
densidad('loellingita',7.1,7.1).
densidad('magnesiochromita',4.5,4.5).
densidad('magnesita',3,3).
densidad('manganita',4.8,4.8).
densidad('manganoneptunita',6.3,6.3).
densidad('marcasita',4.9,4.9).
densidad('marialita',2.8,2.8).
densidad('meionita',2.7,2.7).
densidad('mesolita',2.2,2.2).
densidad('miargirita',7.5,7.5).
densidad('mimetita',6.4,6.4).
densidad('monazita',5.1,5.1).
densidad('natroclita',2.3,2.3).
densidad('nepheline',2.5,2.5).
densidad('neptunita',3.1,3.1).
densidad('nickelina',7.5,7.5).
densidad('nitrato',2,2).
densidad('norbergita',3.2,3.2).
densidad('noseana',2.4,2.4).
densidad('olivina',3.3,3.3).
densidad('olmiita',6,6).
densidad('otavita',4.2,4.2).
densidad('paradamita',6.8,6.8).
densidad('pentlandita',4.9,4.9).
densidad('fosgenita',6.2,6.2).
densidad('polibasita',6.1,6.1).
densidad('powellite',6.2,6.2).
densidad('prehnita',2.8,2.8).
densidad('psilomelana',4.9,4.9).
densidad('pumpellyita',3,3).
densidad('piromorfita',6.2,6.2).
densidad('pirita-piropo',3.5,3.5).
densidad('raspita',5.4,5.4).
densidad('romanecita',5.3,5.3).
densidad('sal_amoniaco',1.4,1.4).
densidad('esqueleto',5.9,5.9).
densidad('schorlomita',6.8,6.8).
densidad('scolecita',2.3,2.3).
densidad('escorzalita',4,4).
densidad('serandita',3.3,3.3).
densidad('shattuckita',4.2,4.2).
densidad('silimanita',3.2,3.2).
densidad('kuterido',6.6,6.6).
densidad('smithsonita',4.5,4.5).
densidad('espersaritina',9,9).
densidad('espessartina',3.7,3.7).
densidad('estaurolita',3.7,3.7).
densidad('estellerita',2,2).
densidad('estefanita',6.2,6.2).
densidad('estibarsen',4.3,4.3).
densidad('estibiconita',4.5,4.5).
densidad('estibnita',6.6,6.6).
densidad('estishovita',4.3,4.3).
densidad('estolzita',5.4,5.4).
densidad('estrengita',3.6,3.6).
densidad('estroncinita',3.5,3.5).
densidad('silvanita',7.6,7.6).
densidad('tantalita',7.9,7.9).
densidad('telurio',6.3,6.3).
densidad('tephroita',3.1,3.1).
densidad('tetrahedrita',6,6).
densidad('tenardita',2.8,2.8).
densidad('torita',6.3,6.3).
densidad('torogummita',3.3,3.3).
densidad('titanita',3.6,3.6).
densidad('topacio',3.5,3.5).
densidad('turmalina',2.9,3.2).
densidad('uvarovita',3.5,3.5).
densidad('uvita',3.3,3.3).
densidad('vanadinit',6.2,6.2).
densidad('variscita',2.5,2.5).
densidad('vesuvianita',3.3,3.3).
densidad('vivianita',2.8,2.8).
densidad('wavellite',2.7,2.7).
densidad('willemita',4.3,4.3).
densidad('witherita',4.4,4.4).
densidad('wolframita',7.2,7.2).
densidad('wollastonita',2.8,2.8).
densidad('wulfenita',6,6).
densidad('xenotima',4.4,4.4).
densidad('circon',4.7,4.7).
densidad('zoisita',3.3,3.3).
densidad('anatasa',3.8,3.8).
densidad('agata',2.5,2.7).
densidad('albite',2.6,2.6).
densidad('andesina',2.6,2.7).
densidad('anortoclasa',2.6,2.7).
densidad('arsenopirita',7.0,7.5).
densidad('axinita',3.2,3.3).
densidad('benitoita',3.6,3.6).
densidad('borax',2.4,2.4).
densidad('bytownita',2.7,2.7).
densidad('chalcanthita',1.9,1.9).
densidad('calcedonia',2.6,2.6).
densidad('cobalto',5.9,5.9).
densidad('cyanotrichita',3.7,3.7).
densidad('epistilbita',2.3,2.3).
densidad('heulandita',2.2,2.2).
densidad('caolinita',2.6,2.6).
densidad('cianita',3.6,3.6).
densidad('labradorita',2.7,2.7).
densidad('laumontita',2.1,2.1).
densidad('lazurita',2.9,2.9).
densidad('litiophilita',4.3,4.3).
densidad('luzonita',3.3,3.3).
densidad('metavariscita',2.4,2.4).
densidad('natrojarosita',2.5,2.5).
densidad('oligoclasa',2.6,2.6).
densidad('pararealgar',4.9,4.9).
densidad('plagioclasa',2.7,2.7).
densidad('pirargirita',6,6).
densidad('realgar',3.5,3.5).
densidad('rodonita',3.6,3.6).
densidad('escapolita',2.6,2.6).
densidad('serpentina',2.6,2.6).
densidad('siderita',3.8,3.8).
densidad('acanthita',7,7).
densidad('apofilita',2.3,2.3).
densidad('tridimita',2.3,2.3).
densidad('turquesa',2.6,2.6).
densidad('aguamarina',2.7,2.7).
densidad('arsenico',5.7,5.7).
densidad('caliza',2.7,2.7).
densidad('cinabrio',8.1,8.1).
densidad('corindon',4,4).
densidad('dolomita',2.9,2.9).
densidad('gibbsita',2.4,2.4).
densidad('hematita',5.3,5.3).
densidad('jadeita',3.3,3.3).
densidad('jaspe',2.6,2.6).
densidad('limonita',4.3,4.3).
densidad('metacinnabar',8.1,8.1).
densidad('opala',2,2).
densidad('pezzottaita',3,3).
densidad('fenacita',3,3).
densidad('pyroxmangita',3.2,3.2).
densidad('rammelsbergita',6.7,6.7).
densidad('rodocrosita',3.6,3.6).
densidad('rutilo',4.2,4.2).
densidad('trekita',3.2,3.2).
densidad('esferocobaltita',5.7,5.7).




% -------------------------------------------------------------------
% Predicado para verificar si un valor está dentro de un rango
% -------------------------------------------------------------------
dentro_de_rango(Valor, Min, Max) :-
    nonvar(Valor),
    number(Valor),
    Valor >= Min,
    Valor =< Max.


% -------------------------------------------------------------------
% Búsqueda Exacta
% -------------------------------------------------------------------
adivinar_mineral(GrupoCristalino, Color, Raya, Dureza, Densidad, Mineral) :-
    (   nonvar(GrupoCristalino),
        nonvar(Color),
        nonvar(Raya),
        nonvar(Dureza),
        nonvar(Densidad)
    ->  
        grupo_cristalino(Mineral, GrupoCristalino),
        color(Mineral, Color),
        raya(Mineral, Raya),
        dureza(Mineral, MinD, MaxD), dentro_de_rango(Dureza, MinD, MaxD),
        densidad(Mineral, MinDe, MaxDe), dentro_de_rango(Densidad, MinDe, MaxDe)
    ;   
        write('Por favor, complete todos los campos para realizar una búsqueda exacta.'), nl,
        fail).
% -------------------------------------------------------------------
% Búsqueda Normal
% -------------------------------------------------------------------
adivinar_probabilidad(GrupoCristalino, Color, Raya, Dureza, Densidad, Resultados) :-
    (   al_menos_un_valor(GrupoCristalino, Color, Raya, Dureza, Densidad)
    ->  
        findall(
            Mineral-Probabilidad,
            calcular_probabilidad1(GrupoCristalino, Color, Raya, Dureza, Densidad, Mineral, Probabilidad),
            ProbabilidadesParciales),
        (   ProbabilidadesParciales \= []
        ->  normalizar_probabilidades(ProbabilidadesParciales, Resultados)
        ;   Resultados = [])
    ;   
        write('Por favor, ingrese al menos un atributo para realizar la búsqueda.'), nl,
        fail).

calcular_probabilidad1(GrupoCristalino, Color, Raya, Dureza, Densidad, Mineral, Probabilidad) :-
    grupo_cristalino(Mineral, GC),
    color(Mineral, Col),
    raya(Mineral, Ry),
    dureza(Mineral, MinD, MaxD),
    densidad(Mineral, MinDe, MaxDe),

    contar_match1([
        (nonvar(GrupoCristalino), GrupoCristalino = GC),
        (nonvar(Color), Color = Col),
        (nonvar(Raya), Raya = Ry),
        (nonvar(Dureza), dentro_de_rango(Dureza, MinD, MaxD)),
        (nonvar(Densidad), dentro_de_rango(Densidad, MinDe, MaxDe))
    ], Matches),

    contar_caracteristicas_dadas([GrupoCristalino, Color, Raya, Dureza, Densidad], TotalAtributos),

    (TotalAtributos > 0 -> Probabilidad is Matches / TotalAtributos; Probabilidad is 0).
    
contar_match1([], 0).
contar_match1([Condicion|T], Matches) :-
    (Condicion -> contar_match1(T, Rest), Matches is Rest + 1;
    contar_match1(T, Matches)).

% -------------------------------------------------------------------
% Búsqueda Estricta
% -------------------------------------------------------------------
buscar_estricto(GrupoCristalino, Color, Raya, Dureza, Densidad, Resultados) :-
    (   al_menos_un_valor(GrupoCristalino, Color, Raya, Dureza, Densidad)
    ->  
        (   setof(
                Mineral-ProbabilidadParcial,
                calcular_probabilidad2(GrupoCristalino, Color, Raya, Dureza, Densidad, Mineral, ProbabilidadParcial),
                ListaProbabilidades),
            ListaProbabilidades \= [],
            normalizar_probabilidades(ListaProbabilidades, Resultados)
        ;   Resultados = [])
    ;   
        write('Por favor, ingrese al menos un atributo para realizar la búsqueda.'), nl,
        fail).

calcular_probabilidad2(GrupoCristalino, Color, Raya, Dureza, Densidad, Mineral, Probabilidad) :-
    grupo_cristalino(Mineral, GC), (var(GrupoCristalino) ; GrupoCristalino = GC),
    color(Mineral, Col), (var(Color) ; Color = Col),
    raya(Mineral, Ry), (var(Raya) ; Raya = Ry),
    dureza(Mineral, MinD, MaxD), (var(Dureza) ; dentro_de_rango(Dureza, MinD, MaxD)),
    densidad(Mineral, MinDe, MaxDe), (var(Densidad) ; dentro_de_rango(Densidad, MinDe, MaxDe)),
    contar_match2([GrupoCristalino-GC, Color-Col, Raya-Ry, Dureza-MinD-MaxD, Densidad-MinDe-MaxDe], Matches),
    contar_caracteristicas_dadas([GrupoCristalino, Color, Raya, Dureza, Densidad], TotalAtributos),
    (TotalAtributos > 0 -> Probabilidad is Matches / TotalAtributos; Probabilidad is 0).

contar_match2([], 0).
contar_match2([Usuario-Real|T], Matches) :-
    (nonvar(Usuario), Usuario = Real -> contar_match2(T, Rest), Matches is Rest + 1;
    contar_match2(T, Matches)).


% -------------------------------------------------------------------
% Herramientas Comunes
% -------------------------------------------------------------------
normalizar_probabilidades(ProbabilidadesParciales, ResultadosNormalizados) :-
    sum_probabilidades(ProbabilidadesParciales, Suma),
    Suma > 0, 
    maplist(normalizar(Suma), ProbabilidadesParciales, ResultadosNormalizados).

normalizar(Suma, Mineral-ProbabilidadParcial, Mineral-ProbabilidadNormalizada) :-
    ProbabilidadNormalizada is ProbabilidadParcial / Suma.

sum_probabilidades([], 0).
sum_probabilidades([_-P|T], Suma) :-
    sum_probabilidades(T, Resto),
    Suma is P + Resto.





contar_caracteristicas_dadas([], 0).
contar_caracteristicas_dadas([H|T], Count) :-
    (nonvar(H) -> contar_caracteristicas_dadas(T, Rest), Count is Rest + 1;
    contar_caracteristicas_dadas(T, Count)).

al_menos_un_valor(GrupoCristalino, Color, Raya, Dureza, Densidad) :-
    nonvar(GrupoCristalino) ;
    nonvar(Color) ;
    nonvar(Raya) ;
    nonvar(Dureza) ;
    nonvar(Densidad).

